repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: coverage
        name: Run Tests with Coverage
        entry: bash -c 'coverage run -m pytest tests --record-mode=none && coverage report'
        language: python
        language_version: default
        types: [python]
        pass_filenames: false
        additional_dependencies:
          [
            coverage,
            requests,
            pytest,
            fastmcp,
            pytest-asyncio,
            pytest-recording,
          ]
      - id: test-agent
        name: Test Agent Configuration
        entry: test_agent_live.sh
        language: script
        pass_filenames: false
