name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Create .env file for live test
      run: |
        echo "GOOGLE_GENAI_USE_VERTEXAI=TRUE" > .env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
